### ISSUE TITLE
zoom maps with mouse wheel

### ISSUE THREAD

**Issue by JocelynDelalande** [JocelynDelalande/wifi-with-me#20]

**Comment by opi** [comment]
Not really kind of zooming map with mouse wheel, because if we enable this feature, we cannot scroll down the page while beeing over the map. On desktop it could be ok, but not on a mobile/tablet experience.

That's really my feeling, and changing this behavior is no more complicated than setting `scrollWheelZoom` to `true` in https://github.com/JocelynDelalande/wifi-with-me/blob/master/assets/map.js#L29

**Comment by kheops2713** [comment]
Agreed with @opi : I find it annoying when a page stops scrolling because my pointer suddenly fell onto the map that has wheelzoom.

**Comment by JocelynDelalande** [comment]
> Agreed with @opi : I find it annoying when a page stops scrolling because my pointer suddenly fell onto the map that has wheelzoom.

At least on the big map, which you don't have to scroll ()

> On desktop it could be ok, but not on a mobile/tablet experience.

I was told that by a coleague of mine the same.

Something I don't get : are not scroll and zoom (pinch) different events on mobile ?

**Comment by bikepunk** [comment]
https://code.ffdn.org/FFDN/wifi-with-me/issues/17
